stages:
    - build
    - push

before_script:
    - docker info
    - export DOCKER_TAG=${CI_BUILD_REF_NAME//\//-}
    - echo $DOCKER_TAG
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build_image:
    stage: build
    script:
        - docker build  -t "$CI_REGISTRY_IMAGE:$DOCKER_TAG"  .

push_image:
    stage: push
    script:
        - docker push "$CI_REGISTRY_IMAGE:$DOCKER_TAG"

